version: '2'

services:
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    image: email-analysis
    build: ./
    command: python main/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
    ports:
      - "8000:8000"